[package]
name = "amazeing-app"
version = "0.1.0"
edition = "2024"
rust-version = "1.85.0"

[dependencies]
amazeing = { version = "*", path = "../amazeing" }
colored = "3.0.0"
macroquad = "0.4.13"

[[bin]]
name = "amazeing-solve"
path = "src/solve.rs"