[package]
name = "amazeing-generator"
version = "0.1.0"
edition = "2024"
rust-version = "1.85.0"

[dependencies]
amazeing = { version = "*", path = "../amazeing" }
macroquad = "0.4.13"

[[bin]]
name = "amazeing-gen"
path = "src/gen.rs"
