[package]
name = "amazeing-generator"
version = "0.1.0"
edition = "2024"


[dependencies]
amazeing = { version = "*", path = "../amazeing" }
colored = "3.0.0"
macroquad = "0.4.13"

[[bin]]
name = "amazeing-gen"
path = "src/main.rs"
