[package]
name = "amazeing-app"
version = "0.1.0"
edition = "2021"

[dependencies]
amazeing = { version = "*", path = "../amazeing" }
colored = "3.0.0"
macroquad = "0.4.13"

[[bin]]
name = "amezing"
path = "src/main.rs"